### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by flowerwOw0316** [CM2Walki/steamcmd#10]
steam@bdab84a666cf:~/steamcmd$ ls
linux32  linux64  package  public  siteserverui  steamcmd.sh
steam@bdab84a666cf:~/steamcmd$ ./steamcmd.sh
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
***** OUT OF MEMORY! attempted allocation size: 147962298 ****
/data/src/tier0/memstd.cpp (2448) : Fatal Assertion Failed: OUT OF MEMORY
/data/src/tier0/memstd.cpp (2448) : Fatal assert failed: /data/src/tier0/memstd.cpp, line 2448.  Application exiting.

_ExitOnFatalAssert
steam@bdab84a666cf:~/steamcmd$

**Comment by CM2Walki** [comment]
Hey @flowerwOw0316,

have you consider the possibility that your system is out of memory? 

> ***** OUT OF MEMORY! attempted allocation size: 147962298 ****
> /data/src/tier0/memstd.cpp (2448) : Fatal Assertion Failed: OUT OF MEMORY

I assume you are probably trying to install something on a very small VPS. Make sure you choose a bigger machine.

**Comment by flowerwOw0316** [comment]
thanks your answer.
My current VPS is 1 core 1G memory, 40g hard disk memory centos8.1
run your docker images 
What is the minimum requirement?

**Comment by CM2Walki** [comment]
Are you running anything else on that VPS? Steamcmd uses around 200 mbs, maybe?

I think you should be fine with a 2 GB VPS.

**Comment by flowerwOw0316** [comment]
thank you
