### ISSUE TITLE
Image steamcmd:root doesn't work

### ISSUE THREAD

**Issue by Flog786** [CM2Walki/steamcmd#2]
I have tried the following command with the default image on GKE and it works :
 app_update 1026340 validate 
but it doesn't work with the root version and returns the following error : 
Steam>login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK

Steam>app_update 1026340 validate
applicationmanager.cpp (3881) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
ERROR! Failed to install app '1026340' (Disk write failure)

**Comment by CM2Walki** [comment]
Hey there,
I was able to replicate your issue in a container. The root access should only help you install additional packages using apt-get. However, steamcmd.sh should be launched by the "steam" user. So just use:

```$ su steam```
```$ ./steamcmd.sh```

Then it should work. 
An example Dockerfile using steamcmd:root can be found here if you ever need it:
https://github.com/CM2Walki/Mordhau/blob/master/stretch/Dockerfile

**Comment by CM2Walki** [comment]
Have you resolved the issue @Flog786?
