### ISSUE TITLE
Password for root user?

### ISSUE THREAD

**Issue by Tao87-04** [CM2Walki/steamcmd#21]
Hi, i must install a extra app. so i try command "su root apt-get update" but without root passwort, i cant do it ^^

I uses Steam Docker release

**Comment by CM2Walki** [comment]
The image doesn't have a root password. There are two options you can use to install additional packages:

1. Go with the image variant `cm2network/steamcmd:root` where the default user is root.

2. Use `docker exec -it -u=root containername bash` on a running container to start a shell as root.

**Comment by Tao87-04** [comment]
ah, i try it in terminal from docker gui. And in this terminal was the password prompt for root. So i try your soloution :)
