### ISSUE TITLE
Is dota 2 server supported?

### ISSUE THREAD

**Issue by max-tgbots** [CM2Walki/steamcmd#27]
I think this was in ID 570, I would like to know if it is currently possible to configure and run it?

**Comment by paul-max-dev** [comment]
According to the STEAM listing I think it is possible.
https://developer.valvesoftware.com/wiki/Dedicated_Servers_List

**Comment by CM2Walki** [comment]
Possibly related to #6.

Sorry, I seem to have missed this issue. According to the link you posted it appears that it indeed has a dedicated server, however it appears that it doesn't support anonymous download, which places it outside this project's scope.

It's kind of weird that a Free 2 Play game doesn't support allow anonymous download, but hey you can still download the server with this image, you just need to login with a user that has Dota 2 on their account. If you ever do make sure to continue this thread and post your findings :).
