### ISSUE TITLE
SteamCMD not found

### ISSUE THREAD

**Issue by Reidond** [CM2Walki/steamcmd#3]
Running this command:
```docker
RUN set -x \
  && "${STEAMCMDDIR}/steamcmd.sh" \
  +login anonymous \
  +force_install_dir ${STEAMAPPDIR} \
  +app_update ${STEAMAPPID} validate \
  +quit
```

Return this:
```docker
/bin/sh: 1: /home/steam/steamcmd/steamcmd.sh: not found
```

**Comment by Reidond** [comment]
[Dockerfile](https://pastebin.com/903bPNLu)

**Comment by CM2Walki** [comment]
I tried to build your `Dockerfile` and it works for me. My guess is that you don't have the latest docker image pulled.
Try:

`docker pull cm2network/steamcmd:root`

And then build again:
```Step 7/13 : RUN set -x   && "${STEAMCMDDIR}/steamcmd.sh"   +login anonymous   +force_install_dir ${STEAMAPPDIR}   +app_update ${STEAMAPPID} validate   +quit
 ---> Running in 2f84c08e4418
+ /home/steam/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/steam/arma3 +app_update 233780 validate +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 49996 KB)...```

**Comment by Reidond** [comment]
So what i found out:

- Your base image for some reason does not work on Docker for Windows
- And on linux it works

**Comment by Reidond** [comment]
For some reason wget command does not execute. But it works when running it by hand in container

**Comment by CM2Walki** [comment]
>     * Your base image for some reason does not work on Docker for Windows
Would be cool if you could find out what exactly the issue is, I'm not a fan or user of Docker for Windows, so I can't help you out there.

> For some reason wget command does not execute. But it works when running it by hand in container
Is that for Docker on Windows?

**Comment by Reidond** [comment]
> Is that for Docker on Windows?
Yes

**Comment by Reidond** [comment]
So for anyone that is looking for the solution: just use linux containers instead of windows containers in Docker for Windows
