### ISSUE TITLE
login fails after MFA: Failed to write file after download (2)

### ISSUE THREAD

**Issue by shichen85** [CM2Walki/steamcmd#30]
Hello,

I was trying to generate Sentry files, but after inputting the MFA code, I got the error `Failed to write file after download (2)`:

```
docker run -it --name=steamcmd cm2network/steamcmd:root bash
root@c18211f635d1:/home/steam/steamcmd# ./steamcmd.sh +login username password +quit
...Downloading update...
Loading Steam API...OK
Logging in user 'username ' to Steam Public...
This computer has not been authenticated for your account using Steam Guard.
Please check your email for the message from Steam, and enter the Steam Guard
 code from that message.
You can also enter this code at any time using 'set_steam_guard_code'
 at the console.
Steam Guard code:4AXYX
OK
Waiting for client config...OK
Waiting for user info...src/clientdll/remotestoragefilesynccontext.cpp (859) : Assertion Failed: Failed to write file after download (2)

src/clientdll/userremotestorage.cpp (3975) : bRet
OK
```

Not sure how to get past this. Would appreciate any advice!

**Comment by CM2Walki** [comment]
See the [#readme](https://github.com/CM2Walki/steamcmd/blob/master/README.md). You are utilizing the root tag of the `cm2network/steamcmd` image. The steamcmd binary and directory are owned by the unprivileged steam user, so if you execute the binary as root, it will break. 

There are two options to solve this: 

1. Switch users using `su steam` in your current setup then execute your command again
2. Use the `cm2network/steamcmd:steam` or just `cm2network/steamcmd` tag, that will make the container enter directly as the steam user.

I hope this solves your issue.
