### ISSUE TITLE
Are applications that only run on windows supported?

### ISSUE THREAD

**Issue by ThatNerdUKnow** [CM2Walki/steamcmd#32]
I want to test out creating a rising storm 2 server with this image, the server depends on being installed on a windows machine. Is it possible to install this app?

**Comment by CM2Walki** [comment]
If you use Docker for Windows, you should be able to, but only if you use Linux Containers. Note that Linux Containers on Docker for Windows are heavily dependent on hardware virtualization, which means that they will perform poorly (also some features like `--net=host` are not available). However, it will run.
