### ISSUE TITLE
Volume should be created by user instead of dockerfile

### ISSUE THREAD

**Issue by LaurentLardenois** [CM2Walki/steamcmd#33]
Making the volume to persist the data should be up to the user, I am currently using this image to make an Arma 3 server in my k8s cluster and the automatically created volume just makes me use more disk space and it cannot be changed/unmade. It should be up to the user to create the volume if they want to (it's also easy so it's not like you're adding more complexity if you do), and this would make the docker image more versatile and better to work with, and inherit from.

**Comment by CM2Walki** [comment]
Related to #34 #35

**Comment by CM2Walki** [comment]
Merged. Added paths for optional volumes to readme for reference. I will rebuild the images, once Docker Hub is back up, it seems to be having problems right now. 

Thanks for the contribution

**Comment by CM2Walki** [comment]
Images have been rebuilt.
