### ISSUE TITLE
Steamcmd Linux version app 258550

### ISSUE THREAD

**Issue by massimo1980** [CM2Walki/steamcmd#40]
Hi there,
( sorry if i'm asking in the wrong place )
after updating app 258550  can't connect to my dedicated server anymore. my client is uptodate through Steam app.
updating with:
steamcmd +force_install_dir /home/steam/rust_server/ +login anonymous +app_update 258550 validate +quit

but when i try to connect the client, i continue to get this error:
Kicking IP:PORT/SteamID/Zeta - their protocol is 2345 not 2347
IP:PORT/SteamID/Zeta kicked: Wrong Connection Protocol: Client update required!

Thanks for your support
Regards

**Comment by CM2Walki** [comment]
> Wrong Connection Protocol: Client update required!

This indicates that your client is out-of-date not your server.

**Comment by massimo1980** [comment]
as i wrote in the previous message, my client is kept update directly by Steam application. There isn't any new update
with the actual version of my client, i can play on official servers with no problems.
if i try to connect to my dedicated server, i receive that error

**Comment by massimo1980** [comment]
seems that now it is working
i close it
