### ISSUE TITLE
Curious error 0x202 of SteamCMD v1658944597

### ISSUE THREAD

**Issue by jalho** [CM2Walki/steamcmd#41]
This issue doesn't necessarily have anything to do with this repository. I have also tried posting about this [on Steam forums](https://steamcommunity.com/discussions/forum/14/3464975249567851250/). Posting here just in case this is a more active SteamCMD forum.

## The issue: Curious SteamCMD error 0x202

I tried installing [Rust](https://store.steampowered.com/app/252490/Rust/) dedicated server from within a container made from `cm2network/steamcmd:root` on two Linux machines. On one of the machines the installation completes successfully but on the other one it fails with error status _0x202_. Filesystems, user permissions and issued commands should be identical due to containerization, and both machines have plenty of disk space. What could be causing this discrepancy?

SteamCMD and Docker versions:
```
Steam Console Client (c) Valve Corporation - version 1658944597
Docker version 20.10.17, build 100c70180f
```

**Comment by CM2Walki** [comment]
Did you execute the `steamcmd.sh` as user `root` by any chance? That usually leads to weird behavior like this for me.

**Comment by jalho** [comment]
I ran a bash script as `steam` that ran the `steamcmd.sh`.

Dockerfile:
```dockerfile
FROM cm2network/steamcmd:root

# install dependencies:
# at least sqlite3 seem to be required by `RustDedicated` as of Jul 2022
# TODO: add the rest of the dependencies, if any!
RUN apt-get update; \
    apt-get upgrade -y \
    && apt-get install -y sqlite3

# as of Jul 2022 the base image comes with user `steam`
USER steam
COPY fetch-server-and-start.sh /home/steam/
WORKDIR /home/steam
```

Commands:
```
$ docker build --tag rust-server . && docker run -ti rust-server /bin/bash
steam@3a3e34cce070:~$ whoami
steam
steam@3a3e34cce070:~$ bash fetch-server-and-start.sh
Fetching the Rust server with SteamCMD...
...
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '258550' state is 0x202 after update job.
Fetching with SteamCMD done.
```
where `fetch-server-and-start.sh` is:
```bash
#!/bin/bash

echo "Fetching the Rust server with SteamCMD..."
/home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/rust-server +login anonymous +app_update 258550 +quit
echo "Fetching with SteamCMD done."
```

These exact steps reproduce the issue; works fine on one of my machines but not on the other one.
