### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by FerLuisxd** [CM2Walki/steamcmd#43]
It would be nice that you guys release the binaries for ARM64 so it is easier to host servers on those types of architectures (like oracle's or raspberry pi 4)

**Comment by CM2Walki** [comment]
steamcmd is a binary maintained by Valve. This project is just a Docker wrapper around it, there is no native ARM64 binary available, so there will not be an image for it. I doubt that there are many ARM game servers anyway, most of them are x86_64.

**Comment by rauldeheer** [comment]
Any news?

**Comment by FerLuisxd** [comment]
Valve has the be the one to support it
