### ISSUE TITLE
`./steamcmd.sh: line 39:   133 Segmentation fault      $DEBUGGER "$STEAMEXE" "$@"`

### ISSUE THREAD

**Issue by devioa** [CM2Walki/steamcmd#51]
![image](https://github.com/CM2Walki/steamcmd/assets/38558065/18f653c5-5c53-4434-8fe4-b1800e1f0f25)

**Comment by CM2Walki** [comment]
Not enough information, but I assume it's `Docker for Windows` or `Ubuntu WSL`?

**Comment by devioa** [comment]
I now know the reason. `steamcmd` only has 32-bit executable binary files, while OpenWrt only supports 64 bit programs, so it cannot run.
