### ISSUE TITLE
[Feature Request] Please add Debian 12 image/support

### ISSUE THREAD

**Issue by jammsen** [CM2Walki/steamcmd#54]
Hello @CM2Walki 

Im using your Docker-base-image to make https://github.com/jammsen/docker-palworld-dedicated-server an reality and i really like it.

While going through some issues this [comment](https://github.com/jammsen/docker-palworld-dedicated-server/issues/105#issuecomment-1934672870) did arise, in which Mac users that using this base image getting problems with the old version of SED 4.7.1 because its Debian 11 and oldstable. This could be solved in providing a Debian 12 version of this image, which has already SED 4.9.1 included (including the Bug-Fix).

Would it be possible to publish the new Debian 12 version also, aside from the Debian 11 version?

**Comment by CM2Walki** [comment]
Done

**Comment by jammsen** [comment]
Thanks!
