### ISSUE TITLE
[Enhancement] Introduce the ability to pin to a Debian version

### ISSUE THREAD

**Issue by thijsvanloef** [CM2Walki/steamcmd#56]
Hi! 

I've build an image depending on your awesome image, however the lacking ability to pin to a specific version introduced some issues when you updated from Debian bullseye to Debian bookworm. 
If possible I would like to have an option to pin to a specific version like: `cm2network/steamcmd:deb11-root`

**Comment by CM2Walki** [comment]
Yeah, the moment I renamed the directory I thought that might be an issue with backwards compatibility. I'll introduce debian specific tags.

**Comment by CM2Walki** [comment]
The new tags are ready:
```
cm2network/steamcmd:root-bullseye
cm2network/steamcmd:steam-bullseye
```

**Comment by thijsvanloef** [comment]
You are amazing!
