### ISSUE TITLE
Can't start server with an entrypoint.sh

### ISSUE THREAD

**Issue by lennard7001** [CM2Walki/steamcmd#7]
Hey,

I'm currently trying to create a GMod image based on this one.  But if i try to start my Server through an entrypoint.sh it fails like this:

```
gmod-server    | Auto detecting CPU
gmod-server    | Using default binary: ./srcds_linux
gmod-server    | Server will auto-restart if there is a crash.
gmod-server    | Setting breakpad minidump AppID = 4000
gmod-server    | [S_API] SteamAPI_Init(): Loaded 'steamclient.so' OK.
gmod-server    | CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
gmod-server    | CApplicationManagerPopulateThread took 1 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
gmod-server    | [S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.
```

But the scripts works perfectly fine after I exec into the container and run it.

Maybe you also had the problem and know how to fix it.

Here is the link to the issue in my repo if you need more info.
https://github.com/lennard7001/docker-gmod/issues/1

**Comment by gauravkanojia** [comment]
Hey, I don't want to advertise or break any rules, but I really found https://github.com/GameServerManagers/LinuxGSM very helpful for hosting servers. Maybe some logic can be extracted from there for running.

**Comment by CM2Walki** [comment]
Hey @lennard7001,

can you try latest? Was it maybe related to CM2Walki/CSGO#1?

**Comment by lennard7001** [comment]
I found the problem, it's related to this one https://github.com/Facepunch/garrysmod-issues/issues/2343.

**Comment by StalkerRaftik** [comment]
@lennard0711 Don't you have problems with source_logger? I have this:
```
8 Illegal instruction     (core dumped) 
./source_logger -game garrysmod -norestart -port 27015 +maxplayers 128 +map gm_construct +host_workshop_collection 2760527539 +gamemode darkrp +r_hunkalloclightmaps 0
```
